import { mkdir, stat, writeFile } from 'node:fs/promises'
import { dirname, join, resolve } from 'node:path'
import { assertContained } from './paths.js'
import type { PromotionSpec } from './types.js'

function assertPackageName(value: string): void {
  if (!/^(?:@[a-z0-9][a-z0-9._-]*\/)?[a-z0-9][a-z0-9._-]*$/.test(value)) throw new Error('Invalid npm package name')
}

function assertIdentifier(value: string, label: string): void {
  if (!/^[A-Za-z_$][\w$-]*$/.test(value)) throw new Error(`Invalid ${label}`)
}

async function writeNew(path: string, content: string): Promise<void> {
  await mkdir(dirname(path), { recursive: true })
  await writeFile(path, content, { encoding: 'utf8', mode: 0o600, flag: 'wx' })
}

export async function promotePackage(workspaceRoot: string, spec: PromotionSpec): Promise<{ destination: string; files: string[] }> {
  assertPackageName(spec.packageName)
  assertIdentifier(spec.pluginName, 'plugin name')
  assertIdentifier(spec.rowId, 'row id')
  const destination = assertContained(resolve(workspaceRoot), resolve(workspaceRoot, spec.destination))
  const exists = await stat(destination).then(() => true, () => false)
  if (exists) throw new Error(`Promotion destination already exists: ${destination}`)
  const manifest = {
    name: spec.packageName,
    version: '0.1.0',
    description: spec.description,
    type: 'module',
    main: 'lib/index.js',
    types: 'lib/index.d.ts',
    files: ['lib/', 'cordis.patch.yml', 'README.md'],
    dsh: { bundle: { patch: './cordis.patch.yml' } },
    scripts: {
      build: 'tsc -p tsconfig.json',
      typecheck: 'tsc -p tsconfig.json --noEmit',
      test: 'vitest run',
      prepare: 'npm run build',
    },
    peerDependencies: { '@deepseek-ai/cordis': '^4.0.1' },
    devDependencies: {
      '@deepseek-ai/cordis': '4.0.1',
      '@types/node': '^22.20.0',
      typescript: '^6.0.3',
      vitest: '^4.1.8',
    },
    license: 'MIT',
  }
  const tsconfig = {
    compilerOptions: {
      target: 'ES2023', module: 'NodeNext', moduleResolution: 'NodeNext', strict: true,
      declaration: true, outDir: 'lib', rootDir: 'src', skipLibCheck: true,
    },
    include: ['src/**/*.ts'],
  }
  const files: Array<[string, string]> = [
    ['package.json', `${JSON.stringify(manifest, null, 2)}\n`],
    ['tsconfig.json', `${JSON.stringify(tsconfig, null, 2)}\n`],
    ['src/index.ts', spec.source.endsWith('\n') ? spec.source : `${spec.source}\n`],
    ['cordis.patch.yml', `- insert:\n    - id: ${spec.rowId}\n      name: ${spec.packageName}\n`],
    ['README.md', `# ${spec.packageName}\n\n${spec.description}\n\nGenerated by DSH Forge from a verified design. Dynamic Cordis source is not a release artifact; this package is the reproducible source form.\n`],
    ['tests/plugin.spec.ts', `import { describe, expect, it } from 'vitest'\nimport * as plugin from '../src/index.js'\n\ndescribe('${spec.pluginName}', () => {\n  it('exports an apply function', () => {\n    expect(typeof plugin.apply).toBe('function')\n  })\n})\n`],
  ]
  for (const [path, content] of files) await writeNew(join(destination, path), content)
  return { destination, files: files.map(([path]) => path) }
}
